# data source config
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/camunda
    username: camunda
    password: camunda
#    testOnBorrow=true
#    validationQuery=SELECT 1
#  url: jdbc:h2:mem:camunda
#  username: sa
#  password: sa
#  driverClassName: org.h2.Driver
  #url: jdbc:postgresql://localhost/assuriti
  #username:
# logging config
# camunda config
camunda:
  bpm:
    history-level: audit
flyway:
  baseline-on-migrate: true
  check-location: true
  locations: classpath:db/migration/postgres

