# data source config
spring:
  datasource:
  url: jdbc:h2:mem:camunda
  username: sa
  password: sa
  driverClassName: org.h2.Driver
# logging config
# camunda config
camunda:
  bpm:
    history-level: audit
