# data source config
spring:
  datasource:
    testOnBorrow=true
    validationQuery=SELECT 1
#  url: jdbc:h2:mem:camunda
#  username: sa
#  password: sa
#  driverClassName: org.h2.Driver
  #url: jdbc:postgresql://localhost/assuriti
  #username:
# logging config
# camunda config
camunda:
  bpm:
    history-level: audit
flyway:
  baseline-on-migrate: true