# data source config
spring:
  datasource:
    url: jdbc:h2:mem:camunda;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  # h2 in memory database access
  h2:
    console:
      enabled: true
# logging config
# camunda config
camunda:
  bpm:
    history-level: audit
    authorization-enabled: true
# required fof flyway with H2
flyway:
  schemas: PUBLIC

#logging:
#  level:
#    org.camunda: DEBUG